version: '3'
services:
  redis:
    image: redis:latest
    # container_name: redis
    # hostname: redis
    ports:
     - "6379:6379"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   build: .
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - 8081:8081
